---
env:
  contexts:
  - name: "dast"
    urls: []
    includePaths:
    - "https://juice-shop.herokuapp.com/#/"
    excludePaths: []
    authentication:
      method: "form"
      parameters:
        loginPageUrl: ""
        loginRequestUrl: "https://juice-shop.herokuapp.com/#/login"
        loginRequestBody: ""
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: "cookie"
      parameters: {}
    technology:
      exclude: []
    users:
    - name: "edu"
      credentials:
        password: "Senha123"
        username: "edu"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
    disableAllRules: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters: {}
  policyDefinition:
    rules: []
  name: "activeScan"
  type: "activeScan"
- parameters:
    template: "risk-confidence-html"
    reportDir: "C:\\Users\\EduardoMachado"
    reportTitle: "ZAP Scanning Report"
    reportDescription: ""
  name: "report"
  type: "report"
